# Generated by Django 3.0.2 on 2020-02-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('category_name', models.CharField(max_length=150, null=True, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('poster_url', models.CharField(max_length=150, null=True, verbose_name='poster_url')),
                ('carousel_url1', models.CharField(max_length=150, null=True, verbose_name='poster_url')),
                ('carousel_url2', models.CharField(max_length=150, null=True, verbose_name='poster_ur2')),
                ('carousel_url3', models.CharField(max_length=150, null=True, verbose_name='poster_ur3')),
                ('carousel_url4', models.CharField(max_length=150, null=True, verbose_name='poster_ur4')),
                ('carousel_url5', models.CharField(max_length=150, null=True, verbose_name='poster_ur5')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('latitude', models.CharField(max_length=250, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=250, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('user_name', models.CharField(max_length=150, null=True, verbose_name='user_name')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('price', models.CharField(max_length=10, null=True, verbose_name='price')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='description')),
                ('location', models.DateTimeField(max_length=150, null=True, verbose_name='location')),
                ('category', models.ManyToManyField(null=True, to='dp.Categories', verbose_name='category')),
                ('images', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Images', verbose_name='location')),
            ],
        ),
    ]
