# Generated by Django 3.0.2 on 2020-02-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(to='dp.Categories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Locations', verbose_name='location'),
        ),
    ]
