# Generated by Django 3.0.2 on 2020-02-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_auto_20200201_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=550, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Images', verbose_name='images'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('message', models.CharField(max_length=120, verbose_name='message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.Users', verbose_name='user_id')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='comments',
            field=models.ManyToManyField(to='dp.Comments', verbose_name='comments'),
        ),
    ]
