# Generated by Django 3.0.2 on 2020-02-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0003_auto_20200201_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='dp.Comments', verbose_name='parent_comment'),
        ),
    ]
